ABO
蹄A乐O


蒋舒婷的易感期要到了，可是作为伴侣的韩家乐却还在外地。

“乐乐姐姐，我到时候会很难受的，你可不可以回来陪陪我。”

蒋舒婷惯会对韩家乐使用撒娇的语气，韩家乐也很吃蒋舒婷这一套。

但这一次韩家乐却出奇的拒绝了蒋舒婷。

“蒋舒婷，我现在是在出差，哪能说回去就回去。乖啦，自己解决一下先吧。”

蒋舒婷没能得到韩家乐的同意，也是失落上了。




但蒋舒婷总是鬼点子多。

韩家乐不能回来，不代表蒋舒婷不能过去。

想到这个，蒋舒婷就准备开始美美收拾行李了。

虽然有一定的风险在。

收拾好行李后，问题倒是来了。

韩家乐住在哪个酒店。

蒋舒婷也想到直接问韩家乐是行不通的，反而还会招来臭骂一顿。

突然就想起自己不是还认识几个韩家乐的同事吗，就去他们那旁敲侧击了。

得到准确的地址和房间号后，蒋舒婷也是搭上高铁出发去寻找韩家乐了。




她没想着跟韩家乐说她去找她这件事，想到时候直接给韩家乐一个惊喜。

不知道韩家乐到时候看见她会是什么表情，但一定很惊讶的。




过了三个小时，蒋舒婷乘坐的高铁到站了。

她现在要打车过去韩家乐的酒店了。

到了韩家乐的酒店楼下后，韩家乐的那几个同事也是偷偷跟蒋舒婷说了韩家乐在房间里，让她上去找韩家乐。

到韩家乐房间门前，蒋舒婷还是礼貌的按了下门铃。

等韩家乐开了门后，蒋舒婷已经抱上她了。

这味道，韩家乐再熟悉不过，甚至不用看清来人是谁，她都知道是蒋舒婷来找她了。

“不是说了让你在家等着吗。”

“可是我真的不想离开你，我就想要你帮我。”

好吧，易感期确实有点粘人的。

“那你这些天就先待在酒店吧，去哪要记得说。”

“好的。”




平时韩家乐在工作时，蒋舒婷就在一旁看着。

但也少不了一些动手动脚。

时不时就摸摸韩家乐的脸，拉拉韩家乐的手，碰这碰那的，韩家乐也纵容着蒋舒婷的动作。

没办法，自家的A只能自己宠。




也是突然的，蒋舒婷易感期到了。

房间里也开始弥漫着蒋舒婷的信息素。

蒋舒婷拉扯了几下韩家乐的袖子。

“乐乐姐姐，难受。”

看着蒋舒婷两眼泪汪汪的，韩家乐没法开口拒绝，只能点点头。

释放信息素安抚一下对方后，两人简单清洗一下便开始了“帮助”。

韩家乐尝试用手先解决一次，摸到蒋舒婷的腺体后便开始慢慢撸动。

但明显见效慢。

蒋舒婷又萌生着想让韩家乐口交的想法。

想法很美好，现实不敢提。

但韩家乐像是有读心术，她好像知道蒋舒婷在想什么。

“就…这一次。”

韩家乐也难以启齿。

尝试吞入腺体后，舌头围着柱身打转，韩家乐的速度一直都不算快，但韩家乐却“皮”啊。

偷偷用舌尖戳戳顶尖的小洞将它堵起。

这给蒋舒婷的身体带来着极大的刺激。

没忍住，已经将腺液射进了韩家乐口中了。

蒋舒婷慌着去翻找纸巾给韩家乐，但韩家乐把它给吞下了。




现在蒋舒婷是在上位，吻从韩家乐的脖子一直至下腹。

手指轻轻捏住韩家乐一边的乳尖，舌头也在另一边尝试在乳尖打转。

这很让韩家乐难受。

轻轻拍了拍蒋舒婷的背部，示意让她别玩了。

蒋舒婷起身后，便拿起腺体一直在韩家乐的洞口徘徊。

快伸进去时，韩家乐才发现蒋舒婷没有带套。

踹了一脚蒋舒婷后就质问了.

“快去带套。”

韩家乐原本以为蒋舒婷只会带一两个过来，简单度过一下易感期便够了。

但谁知蒋舒婷掏出了全新未拆封的一盒，还给韩家乐晃了晃。

拆开塑料膜后，拿出了一个。

但蒋舒婷想让韩家乐帮她戴，就把套递给了韩家乐。

韩家乐也知道什么意思，只能默默拆开包装纸，将套给蒋舒婷戴了进去。

这下没有顾虑的话，蒋舒婷可要开始了。

进行着九浅一深的运动，韩家乐的穴道一直紧紧的包裹着蒋舒婷的腺体，前戏足够，韩家乐的穴道也是湿润，起码让蒋舒婷抽插不是那么困难。

蒋舒婷每次都特别爱听做爱时韩家乐的声音，跟平时真的太不一样了。别样的感觉。

好不容易把韩家乐送进高潮后，一股暖流也包裹着蒋舒婷的腺体，洞穴的收缩也压迫着蒋舒婷缴械投降。

在里面交代后，将腺体退了出来，韩家乐的洞口也开始慢慢流出水。

蒋舒婷对着韩家乐洞口舔舐着。把水一点点收入自己的口腔中。

韩家乐的味道，挺不错的。

蒋舒婷又换上个新套，开启新一轮的攻击。

抽插速度一直在加快，也逼着韩家乐连连的呻吟声。

“蒋舒婷……慢点。”

但蒋舒婷全然当没听到，反而默默加快着速度。

腺体不断的撞击着花心。很快，韩家乐又达到了第二次高潮。

韩家乐又蹬了一脚蒋舒婷，但身体已经没多少力气，蒋舒婷也感觉不到这一脚有什么力量在。

指尖倒是又顺着韩家乐的臀部勾勒至脚尖了。

引得韩家乐一阵酥麻。




在第三次，第四次高潮过后，韩家乐已经没有任何的力气了，叫都没力气叫了。

蒋舒婷却又准备让其第五次了。

“不要……了……会…会被玩坏的。”

蒋舒婷亲上唇后，在韩家乐耳边低语。

“乐乐姐姐，就最后一次。”

其实在第五次时韩家乐已经被操晕过去了，但蒋舒婷仍坚持不懈的努力。




一夜荒唐过后。

韩家乐先醒的，对着面前抱着自己的人就是一脚踹下床。

蒋舒婷也被迷迷糊糊的踹醒。

昨天她们倒是疯狂，避孕套都用了四个。

“蒋舒婷，你就不能节制点吗。”

“我今天还有工作，要外出的，我现在全身都跟散架了一样。”

但蒋舒婷不说话，就静静的望着韩家乐。

“那需要我抱着你去工作吗。”

足够语出惊人。

韩家乐表示有被气到。




待韩家乐出差结束，两人是一起回去的。

一回到家后，收拾好行李，两人也累的瘫在床上。

虽说蒋舒婷本想再做一次的，但韩家乐已经困的睡了过去，只能明天了。

隔天的晚上，她们的卧室也是一直传出喘气声和呻吟声，快凌晨三点仍没停止。

那一夜，蒋舒婷把剩下的六个套全都用完了。




那能说什么，只能说，在工作。
